create extension if not exists "pgcrypto";

create type public.user_role as enum('contratante', 'prestador', 'admin');

create type public.service_status as enum(
  'aberto',
  'em_andamento',
  'concluido',
  'cancelado'
);

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  role public.user_role not null default 'contratante',
  nome text not null,
  cpf text unique,
  data_nascimento date,
  whatsapp text,
  cidade text,
  estado char(2),
  avatar_url text,
  bio text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.categories (
  id bigint generated by default as identity primary key,
  nome text unique not null,
  ativo boolean not null default true
);

create table public.professional_services (
  id uuid primary key default gen_random_uuid (),
  prestador_id uuid not null references public.profiles (id) on delete cascade,
  categoria_id bigint not null references public.categories (id),
  descricao text,
  valor_inicial numeric(10, 2),
  unique (prestador_id, categoria_id)
);

create table public.portfolios (
  id uuid primary key default gen_random_uuid (),
  prestador_id uuid not null references public.profiles (id) on delete cascade,
  titulo text not null,
  descricao text,
  imagem_url text not null,
  created_at timestamptz not null default now()
);

create table public.service_requests (
  id uuid primary key default gen_random_uuid (),
  contratante_id uuid not null references public.profiles (id),
  prestador_id uuid references public.profiles (id),
  categoria_id bigint references public.categories (id),
  titulo text not null,
  descricao text not null,
  cidade text not null,
  estado char(2) not null,
  status public.service_status not null default 'aberto',
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.reviews (
  id uuid primary key default gen_random_uuid (),
  solicitacao_id uuid not null references public.service_requests (id),
  autor_id uuid not null references public.profiles (id),
  avaliado_id uuid not null references public.profiles (id),
  nota smallint not null check (nota between 1 and 5),
  comentario text,
  created_at timestamptz not null default now(),
  unique (solicitacao_id, autor_id)
);

create table public.review_replies (
  id uuid primary key default gen_random_uuid (),
  avaliacao_id uuid unique not null references public.reviews (id) on delete cascade,
  prestador_id uuid not null references public.profiles (id),
  resposta_texto text not null,
  created_at timestamptz not null default now()
);

create table public.favorites (
  contratante_id uuid references public.profiles (id) on delete cascade,
  prestador_id uuid references public.profiles (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (contratante_id, prestador_id)
);

alter table public.profiles enable row level security;

alter table public.categories enable row level security;

alter table public.professional_services enable row level security;

alter table public.portfolios enable row level security;

alter table public.service_requests enable row level security;

alter table public.reviews enable row level security;

alter table public.review_replies enable row level security;

alter table public.favorites enable row level security;

create policy "profiles public" on public.profiles for
select
  using (true);

create policy "own profile" on public.profiles
for update
  using (auth.uid () = id);

create policy "categories public" on public.categories for
select
  using (true);

create policy "services public" on public.professional_services for
select
  using (true);

create policy "own services" on public.professional_services for all using (auth.uid () = prestador_id)
with
  check (auth.uid () = prestador_id);

create policy "portfolio public" on public.portfolios for
select
  using (true);

create policy "own portfolio" on public.portfolios for all using (auth.uid () = prestador_id)
with
  check (auth.uid () = prestador_id);

create policy "requests involved" on public.service_requests for
select
  using (
    auth.uid () = contratante_id
    or auth.uid () = prestador_id
    or prestador_id is null
  );

create policy "client creates request" on public.service_requests for insert
with
  check (auth.uid () = contratante_id);

create policy "reviews public" on public.reviews for
select
  using (true);

create policy "valid completed review" on public.reviews for insert
with
  check (
    auth.uid () = autor_id
    and exists (
      select
        1
      from
        public.service_requests s
      where
        s.id = solicitacao_id
        and s.status = 'concluido'
        and auth.uid () in (s.contratante_id, s.prestador_id)
    )
  );

create policy "replies public" on public.review_replies for
select
  using (true);

create policy "own reply" on public.review_replies for all using (auth.uid () = prestador_id)
with
  check (auth.uid () = prestador_id);

create policy "own favorites" on public.favorites for all using (auth.uid () = contratante_id)
with
  check (auth.uid () = contratante_id);

create or replace function public.handle_new_user () returns trigger language plpgsql security definer
set
  search_path = public as $$ begin insert into public.profiles(id,nome,role) values(new.id,coalesce(new.raw_user_meta_data->>'nome','Usuário'),coalesce((new.raw_user_meta_data->>'role')::public.user_role,'contratante')); return new; end; $$;

create trigger on_auth_user_created
after insert on auth.users for each row
execute procedure public.handle_new_user ();

insert into
  public.categories (nome)
values
  ('Pedreiro'),
  ('Faxineira'),
  ('Encanador'),
  ('Eletricista'),
  ('Pintor'),
  ('Babá'),
  ('Jardineiro')
on conflict do nothing;
